---
- hosts: dev
  become: yes
  tasks:
          - name: Prints various ansible fatcts
            debug:
                    msg: >
                            The default ipv4 address of  {{ ansible_facts.fqdn }}
                            is {{ ansible_facts.default_ipv4.address }}






[admin@linux3 ansible]$ vi complete_facts.yml
          - name: create index.html
            copy:
                    content: "{{ ansible_facts['fqdn'] }}
                    ({{ ansible_facts['default_ipv4']['address'] }}) has been customized by ansible.\n"
                    dest: "{{ web_root }}/index.html"
          - name: firewall service enable and started
            service:
                    name: "{{ firewall_svc }}"
                    state: started
                    enabled: true
          - name: open the port of web server
            firewalld:
                    service: https
                    state: enabled
                    immediate: true
                    permanent: true
          - name: web service enabled and started
            service:
                    name: "{{ web_svc }}"
                    state: started
                    enabled: true
- name: test web server
  hosts: localhost
  become: no
  vars:
          - web_user: guest
          - web_pass: redhat
  vars_files:
          - secret1.yml
  tasks:
          - name: connect web server
            uri:
                    url: http://192.168.56.101/index.html
                    validate_certs: no
                    force_basic_auth: yes
                    user: "{{ web_user }}"
                    password: "{{ web_pass }}"
                    return_content: yes
                    status_code: 200
            register: auth_test
          - debug:
                  var: auth_test.content

