---
- hosts: dev
  become: true
  tasks:
          - name: start httpd service
            service:
                    name: httpd
                    state: stopped

- hosts: web
  become: true
  tasks:
          - name: install mariadb server
            yum:
                    name: mariadb*
                    state: removed
